### ISSUE TITLE
Quarterly partitions

### ISSUE THREAD

**Issue by juananrey** [qonto/postgresql-partition-manager#20]
### Is your feature request related to a problem? Please describe

I would like to have a way to generate Quarterly partitions, because it is what would suit my use case in the best way.

### Describe the solution you'd like

Being able to select `interval: quarterly` on my configuration, which is capable of triggering partitioned tables with the format `YEAR_QUARTER` , as in `2024_q1` , ` 2024_q2` , `2024_q3` , `2024_q4` (similar format to the weekly partitions this project already has)

### Describe alternatives you've considered

None, I am just wondering if that is something that was initially considered or not.

### Additional context

N/A

**Comment by vmercierfr** [comment]
I prepared an implementation at https://github.com/qonto/postgresql-partition-manager/pull/24, should be released this week
